### ISSUE TITLE
Portfolio currencies save

### ISSUE THREAD

**Issue by dib258** [lionsharecapital/lionshare-desktop#33] opened 2017-01-25 15:11 UTC
Hi,

I added in my Portfolio few currencies. Then I changed to only one and a different value. Each time I change the tab (Portfolio -> Prices) or quit the app, when I return I get the old values.

Is there any kind of save ?

**Comment by ztnark** [comment] 2017-01-26 23:34
I believe https://github.com/lionsharecapital/lionshare-desktop/issues/36 is a duplicate of this issue.

**Comment by maksim-s** [comment] 2017-01-29 22:09
Fixed by https://github.com/lionsharecapital/lionshare-desktop/pull/39

**Closed as completed by maksim-s** 2017-01-29 22:09 UTC
Labels: Bug
